### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DOOMOlivera** [valters-tomsons/dsbattery#1]
Hi. Sorry but I don't understand the instructions. What is the status bar? Where do I find it? What do I do then?

**Comment by valters-tomsons** [comment]
This indicator is designed for system status bars that allow custom user modules, like [polybar](https://github.com/polybar/polybar) and [waybar](https://github.com/Alexays/Waybar).

To use `dsbattery` with either of those, you must install them first and then copy contents of [the appropriate module ](https://github.com/valters-tomsons/dsbattery/tree/master/modules) into to your status bar configuration file.
