### ISSUE TITLE
No controller emoji

### ISSUE THREAD

**Issue by FlySlime** [valters-tomsons/dsbattery#2]
As title says, there is no controller emoji when I have it in Polybar. There does exist a controller emoji though when I run the command in my terminal, so this leads me to think that I have to add the font to Polybar - but I do not know what font it is. Could you help me out? This is what fonts are currently used on my Polybar.

```
font-0 = "JetBrains Mono:size=11;4"
font-1 = "Iosevka Nerd Font:size=11;3"
font-2 = "feather:size=12;3"
font-3 = "FontAwesome:size=10"
```

**Comment by valters-tomsons** [comment]
It is definitely a font issue, any font with `video_game` (🎮) emoji will work. I'm currently using `JetBrainsMono Nerd`.

**Comment by FlySlime** [comment]
Alright it took a little while, for some reason `JetBrainsMono Nerd` didn't work for me, neither did any of the others font I had. I used the following resources to deduce what font to use and then had to scale it down for some reason.

- https://github.com/polybar/polybar/wiki/Fonts#find-fonts-for-glyphs
- https://github.com/polybar/polybar/issues/905

This is now my Polybar Config.

```sh
font-0 = "JetBrains Mono:size=11;4"
font-1 = "Iosevka Nerd Font:size=11;3"
font-2 = "feather:size=12;3"
font-3 = "Noto Color Emoji:scale=8:size=12;3"
```

Thanks for the help :stuck_out_tongue_closed_eyes:
